### ISSUE TITLE
yum install fails with "Error: GPG check FAILED"

### ISSUE THREAD

**Issue by techfil** [techfil/ciscoautocert#1]
When installing git and python3.9 yum fails reporting a number of errors similar to this

`"signature hdr data: BAD, no. of bytes(24428) out of range" `

This happens with the latest guestshell image (guestshell.17.09.01a.tar) obtained from cisco.com in Nov 2023.

**Comment by techfil** [comment]
On ARM platforms run this to fix yum install GPG failures:

```
curl https://vault.centos.org/8.5.2111/BaseOS/aarch64/os/Packages/tpm2-tss-2.3.2-4.el8.aarch64.rpm -o tpm2-tss-2.3.2-4.el8.aarch64.rpm
rpm -i tpm2-tss-2.3.2-4.el8.aarch64.rpm
yum update rpm
```

**Comment by rschuknecht** [comment]
Hi, i tried your workaround on a cat8000v with IOS 17.12.3. But it did not work.

what i did:
curl https://vault.centos.org/8.5.2111/BaseOS/aarch64/os/Packages/tpm2-tss-2.3.2-4.el8.x86_64.rpm -o tpm2-tss-2.3.2-4.el8.x86_64.rpm
rpm -i tpm2-tss-2.3.2-4.el8.x86_64.rpm

I got the error: error: 
tpm2-tss-2.3.2-4.el8.x86_64.rpm: not an rpm package (or package manifest):

is there any other way to fix the yum error?

/Robert

**Comment by techfil** [comment]
Is that the exact URL used in curl to download the package?
You shouldn't be able to download X86_64 from the BaseOS/aarch64 directory, so I would first of all check the content of what exactly was downloaded into that rpm file.

On the 17.12.3 Cat8000v do you get the exact "GPG check FAILED" error?
